### ISSUE TITLE
Repository<T>.Update expected behaviour

### ISSUE THREAD

**Issue by johnkattenhorn** [tonysneed/trackable-entities#24]
I've followed the examples for this and maybe I missed it but I'm having to set T.TrackingState = TrackingState.Modified in order to set the changes persisted into the database.

I thought maybe the Repository.Update method would be setting this or is this by design ?

**Comment by tonysneed** [comment]
Thanks for your question. There are two sides to TE: client and server.  The client side is responsible for setting TrackingState, while the server side is responsible for setting EntityState, which is basically informing Entity Framework of an entity's change state, and this is what is performed by the Repository.Update method.  So the answer is that you need both.

Usually on the client you don't have to set TrackingState manually -- the change tracker will do that for you whenever you update a property on an entity that is being change tracked.  This is important because the change tracker will also add the property to the ModifiedProperties collection, which is then interpreted on the server side to apply a partial update, for example, updating just the ProductName column of Product, and not the other columns from the Product table.

**Comment by johnkattenhorn** [comment]
Hi Tony,

Thanks for the confirmation, right now I’m only using the Server Side but will be using the Client Side at some point. I guess tthat’s the reason why Repository.Delete nor Repository.Insert need the TrackingState change as the intent is clear from action you are performing.

Best Regards

John

**Comment by tonysneed** [comment]
Yes, the purpose of Trackable Entities is to track change state across service boundaries.  The TrackingState and ModifiedProperties need to be set in order for changes to be persisted on the server-side.

One of the interesting things on the service-side is support for different kinds of relationships, including 1-M, M-1, 1-1 and M-M.  You'll also want to have a look at LoadRelatedEntities, which populates reference properties for items that have been added.

When you do get to the client-side, you can take advantage of automatic change-tracking throughout a graph of objects.  There is a GetChanges method on the change-tracker, which returns just the changed entities in the graph.  This reduces the amount of data sent over the wire to just what is needed to persist inserts, updated and deletes.  Then when those entities are returned to the client, you can use MergeChanges to merge them back into the original collection of objects.
