### ISSUE TITLE
[VS Project Templates] Add Templates for Use with Reverse POCO Generator

### ISSUE THREAD

**Issue by tonysneed** [tonysneed/trackable-entities#30]
Add templates for use with [Reverse POCO generator] (https://efreversepoco.codeplex.com)

**Comment by tonysneed** [comment]
Deferring this to a future version (post 2.5).

**Comment by VzLOM-Prolog** [comment]
Hello. As i get it correct - this feature will be in next reslease? When you're planning to make it? Thank you

**Comment by tonysneed** [comment]
We wanted to see what interest there is in the feature. And it looks like there is! Any chance you might like to help implement it? :)  It should be relatively straightforward to customize the existing T4 templates for the Reverse POCO Generator.

**Comment by VzLOM-Prolog** [comment]
Actually i will be glad, but maybe a bit later, cos now i have to make working prototype on existing stack asap. 
As i get it correct what we need is to change base t4 reverse poco template to entities derive from EntityBase, add usings etc, change collections to ChangeTrackingCollection. Also there might be some changes to context but i cant get what exaclty? Seems like adding DbContextExtensions and using methods of it instead of original (applychanges instead of savechanges etc? Am i missing smth?

**Comment by tonysneed** [comment]
Sounds good to me. You can take the existing T4 templates as an example. Once you implement it, please feel free to share it with us! We'd like to benefit from your efforts.

**Comment by tonysneed** [comment]
Closing this for now, until someone requests the feature.
