### ISSUE TITLE
Newly added items in collection dont have refernce of parent.

### ISSUE THREAD

**Issue by harrisunderwork** [tonysneed/trackable-entities#48]
Lets say I have a object A that contains property as Collection B. When I add new item to collection B, the newly added object does not have reference to object A.

**Comment by harrisunderwork** [comment]
Example : Lets say I have class Blog containing collection of Posts. If I add a new post, it should contain reference to the blog, but its null.

**Comment by harrisunderwork** [comment]
Okay Tony, I think I found the answer, I need to implement the fixup methods on parent classes.

**Comment by tonysneed** [comment]
Yes, that's it!  Fixup methods will provide what you want here.  Note, however, that these are not strictly necessary, because Entity Framework will fix up the references when retrieving or persisting entities.

Another thing to keep in mind is that you'll most likely want to leave reference properties null on newly created entities, so that only the foreign key value and not the reference entity will be written to the wire, resulting in better performance.  For example, if you have an Order class with Customer and CustomerId properties, only set CustomerId on a new order and leave Customer null.  Trackable Entities on the service-side will populate Customer and return it to the client (via LoadRelatedEntities).

**Comment by harrisunderwork** [comment]
Hi Tony,

The problem is we are executing some rules over the newly created entities,
for that we need to have parent references correctly formed way even before
persistence. You are correct that it will reduce packet size, but we have
some business logic in place due to previous STE.

Do you have T4 template which provides fixup methods ? Or should I write my
own ?

Thanks.

**Comment by tonysneed** [comment]
I think the simplest way would be, when creating a new child entity, set the parent property.  For example: ```new OrderDetail {Order = order}```. I'm not sure if we had C# object initializer syntax when STE's were introduced, but it eliminates the need for adding an overloaded ctor to each child entity via a customized T4 template (which might not be too easy).

If you wanted to do this generically, you could write a method that uses reflection to dynamically set the parent property.  Not too difficult, but it would make a good [Gist](https://help.github.com/articles/about-gists/) if you wanted to give it a try!

**Comment by harrisunderwork** [comment]
Reflection was overkill for this as while adding items, they don't have reference of collections.

I have solved this issue by taking the t4 template from old STE and merging all changes in trackable entities. As such, Fixup methods are available now.

Thanks.
