### ISSUE TITLE
TrackableEntities.EF.6 - ApplyChanges does not work anymore after change from 2.5.0 to 2.5.1

### ISSUE THREAD

**Issue by kaumasse** [tonysneed/trackable-entities#51]
Hi Tony,

first of all a big thank you. Your library solves so many problems I have had to fight with the last years. Please keep it up, it's the only good working solution out there. I would love to use yours for all my upcoming projects. I'll definitely donate and maybe contribute when I'm more familiar with your code.

I have to evaluate solutions about this topic and want to present this one to my colleagues next week for our project. Unfortunately, I have found a bug while updating "TrackableEntities.EF.6" from 2.5.0 to 2.5.1. I hope you can fix it soon and we can use your library.

I try to explain the bug with your database structure. It's a complex insert which affects a 1:1, 1:M and M:N relation.

In 2.5.0 I could create a Customer with CustomerSetting, Order and OrderDetail for an existing Product at once. The Customer was sent to the service method "CreateCustomer", the TrackingState of the Customer was set to "Added" and "ApplyChanges" was called. After that all four objects had the EntityState "Added" in DBContext and were added to database.

| Entity | EntityState |
------------ | -------------
Customer | Added
CustomerSetting | Added
Order | Added
OrderDetail | Added

In 2.5.1 I've done the same but the result is different and not all entities were added to database.

| Entity | EntityState |
------------ | -------------
Customer | Added
CustomerSetting | Added
Order | Unchanged
OrderDetail | Unchanged

The correct behaviour is the one from 2.5.0 right? I only have to set the TrackingsState to the Customer in service method, the EntityStates of the dependent items/children will be resolved by "ApplyChanges", right?

I'm sorry that I can only provide the symptom an not the cause, I haven't had enough time to dig deeper into you code so far. I wrote a test that covers the problem. As you can see, I only set the TrackingState of the customer.

```cs
[Test]
public void Apply_Changes_Bug20150426()
{
	// Arrange
	var context = TestsHelper.CreateNorthwindDbContext(CreateNorthwindDbOptions);
	var nw = new MockNorthwind();

	var customer = new Customer { CustomerId = "ABCD", CustomerName = "ABCD" };

	var customerSetting = new CustomerSetting() { CustomerId = customer.CustomerId, Setting = "Setting1" };
	customer.CustomerSetting = customerSetting;

	var order = new Order() { OrderDate = DateTime.Now };
	customer.Orders = new List<Order>();
	customer.Orders.Add(order);

	var orderDetail = new OrderDetail() { ProductId = nw.Products[0].ProductId, Quantity = 1, UnitPrice = new decimal(1.99) };
	order.OrderDetails = new List<OrderDetail>();
	order.OrderDetails.Add(orderDetail);

	customer.TrackingState = TrackingState.Added;

	// Act
	context.ApplyChanges(customer);

	// Assert
	Assert.AreEqual(EntityState.Added, context.Entry(customer).State);
	Assert.AreEqual(EntityState.Added, context.Entry(customerSetting).State);
	Assert.AreEqual(EntityState.Added, context.Entry(order).State);
	Assert.AreEqual(EntityState.Added, context.Entry(orderDetail).State);
}
```
		
I hope you can help me. Thanks in advance and best regards.

Mathias

**Comment by harrisunderwork** [comment]
Hi John, can you try creating new
ChangeTrackingCollection<Customer>(customer) and then setting tracking
state ? I believe, when you change TrackingState, it first checks whether
Tracking is enabled or not.

**Comment by kaumasse** [comment]
Hi,

thanks for your reply. Well, your suggestion works so far, I mean for this example, but I think it isn't the solution but just a workaround.

I'm confused, in 2.5.0 the following code works without any problems.

```csharp
var customer = new Customer { CustomerId = customerId.ToString(), City = "A", CompanyName = "B", ContactName = "D", Country = "E" };

var setting = new CustomerSetting() { CustomerId = customer.CustomerId, Setting = "Setting1" };
customer.CustomerSetting = setting;

var order = new Order() { OrderDate = DateTime.Now };
customer.Orders.Add(order);

var orderDetail = new OrderDetail() { ProductId = 1, Quantity = 1, UnitPrice = new decimal(1.99) };
order.OrderDetails.Add(orderDetail);

var createdOrder = customerService.CreateCustomerAsync(customer).Result;
```

EntityStates after "ApplyChanges".

| Entity | EntityState |
------------ | -------------
Customer | Added
CustomerSetting | Added
Order | Added
OrderDetail | Added

In 2.5.1 the same code does not work anymore. EntityStates after "ApplyChanges".

| Entity | EntityState |
------------ | -------------
Customer | Added
CustomerSetting | Added
Order | Unchanged
OrderDetail | Unchanged

It works in 2.5.1 if I "enable" the ChangeTracker.

```csharp
var customer = new Customer { CustomerId = customerId.ToString(), City = "A", CompanyName = "B", ContactName = "D", Country = "E" };
                
var changeTracker = new ChangeTrackingCollection<Customer>(customer); 

var setting = new CustomerSetting() { CustomerId = customer.CustomerId, Setting = "Setting1" };
customer.CustomerSetting = setting;

var order = new Order() { OrderDate = DateTime.Now };
customer.Orders.Add(order);

var orderDetail = new OrderDetail() { ProductId = 1, Quantity = 1, UnitPrice = new decimal(1.99) };
order.OrderDetails.Add(orderDetail);

var createdOrder = customerService.CreateCustomerAsync(customer).Result;
```
EntityStates after "ApplyChanges".


| Entity | EntityState |
------------ | -------------
Customer | Added
CustomerSetting | Added
Order | Added
OrderDetail | Added

The thing is that the same code works in 2.5.0 but doesn't work anymore in 2.5.1 after code changes were made on "ApplyChanges" (commit: https://github.com/tonysneed/trackable-entities/commit/e5b7bc0ad0b0bcf9961101b2da56055d27859c72). Furthermore, the samples (https://github.com/tonysneed/trackable-entities/blob/develop/Samples/VS2012/WcfSample/WcfSample.Client.ConsoleApp/Program.cs) show that you don't need a ChangeTracker if you want to create an entity, and the test shown above still fails.

So I think it's a bug, which is related to the code changes and not covered by a test so far. Your suggestion works for this example but does not work really good for my project datastructure (1:1 relation, "Base-Table", "Derived-Table"; cannot provide here, wanted to keep it simple with the existing datastructure everyone knows). So, thanks for your suggestion, but I think it's is just a workaround.

Maybe Tony can take a look at this issue, the test and the code. Thanks everybody.

Best regards Mathias

**Comment by tonysneed** [comment]
Hello @kaumasse and thank you for submitting the issue.  You're correct that there is something of a change in behavior from 2.5.0 to 2.5.1, because we needed to fix a bug #46.  However, the fix is more like correcting a problem we hadn't recognized before.  And this is why your results are different.

That said, once you understand the reason for the change, I think working with the "correct" behavior will be straightforward.  So I'll start by explaining the bug and how we fixed it.

The way EF works is that when you mark an item as Added, it goes all the way down and marks all entities in the object graph as added, whether or not it makes sense to do so.  Up until v2.5.1 we had been correcting EF false Adds at the top level, but not further down the object graph.  (This was simply due to sparse code coverage in our unit tests for this scenario.)  The example that was reported is that if you have an "Added" Order, then EF correctly marks all the details for that order as Added, which is correct.  But it then incorrectly marks the Product for each order detail as also Added.  This is anomaly in EF's disconnected API is rather well-known (at least by folks experienced with using EF in this way), and what you have to do is intelligently correct EF by setting the state for Product back to what it was before, for example, either Unchanged or Modified.  And that's what we implemented in the fix for #46 in v2.5.1.

So, what you have to do in Trackable Entities when setting an entity to Added is pay attention to the relationship types in the object graph.  If the relation 1-M, for example, and order with details, then you just set the order to Added and the details will automatically be added, which is EF's core behavior and is what makes sense in most situations.  But if you have another kind of relationship, you need to be explicit about how you want the state to be set on related entities.  For example, if you have an order detail with a new product, then you would need to explicitly state the TrackingState to Added for that product.  Either TE nor EF would have any way of knowing you are added a new Product or an existing one, unless you so indicate by setting the TrackingState property of the product.

In your example, if you want to add a new Order with a new Customer (M-1) and a new CustomerSetting (1-1), then you would need to explicitly set the TrackingState of Customer to Added.  You can then try not setting CustomerSetting to Added and see if it does get added.  If not, then you have to set CustomerSetting to Added as well, but I can't seem to recall at this point whether that is actually necessary -- without checking to see if we have a unit test for that.

What I would encourage you to do is create one or two unit tests for this scenario and submit them in a Pull Request.  But what I like is to have contributor's first submit an Issue, like you did here.  Then if we agree that a PR would be helpful, to have you go ahead and submit one of those too.  Thanks!

Cheers,
Tony

**Comment by tonysneed** [comment]
@kaumasse, does this answer your issue?

**Comment by kaumasse** [comment]
Hey Tony,

thanks for your quick and sorry for my late reply, the last week was pretty stressful.

I've looked into your test methods, well done so far, many cases covered in my opinion. Thanks for your explanation, I understand the problem with the existing Product in OrderDetail (M:N).

The problem in my last example wasn't CustomerSetting it was Order and OrderDetail. I want to create a new Customer (1:M), with a new Order (1:M), with new OrderDetails (M:N) of an existing Product, referenced by Id not as an object. 

```csharp
var customer = new Customer { CustomerId = randomCustomerId.ToString(), City = "A", CompanyName = "B", ContactName = "D", Country = "E" };

var order = new Order() { OrderDate = DateTime.Now };
customer.Orders.Add(order);

var orderDetail = new OrderDetail() { ProductId = 1, Quantity = 1, UnitPrice = new decimal(1.99) };
order.OrderDetails.Add(orderDetail);

var createdCustomer = customerService.CreateCustomerAsync(customer).Result;
```

If I set TrackingState "Added" to Customer only, he EntityState are this

| Entity | EntityState |
------------ | -------------
Customer | Added
Order | Unchanged
OrderDetail | Unchanged


If I set TrackingState "Added" to Order too, the EntityStates are this

| Entity | EntityState |
------------ | -------------
Customer | Added
Order | Added
OrderDetail | Added


I just want to know whether this is the correct/expected behaviour. I mean they are both 1:M relations "Customer - Order" and "Order - OrderDetail". Is it false/dangerous to apply the state from Customer down to OrderDetail automatically? 

So, in the end I have to take care on the server about the relations and have to set the state of some children manually, correct?

If the current behaviour is correct, you can close this issue. 

Best regards Mathias

**Comment by tonysneed** [comment]
Hello Mathias,

Thanks for your question, and I'm happy to clarify.  The behavior for setting state should depend on the type argument you supply to ```ChangeTrackingCollection<T>```.  If T is **Customer**, then adding a new ```Customer``` and calling ```ApplyChanges``` should walk down to add both order and details.

In terms of process, the best way is for you to fork the Trackable Entities repo, create a new branch, then add a failing unit test.  After that, you can push your commits up to GitHub and create a [pull request](https://help.github.com/articles/creating-a-pull-request).  Then I can simply look at your unit test and verify the conditions, etc.  Do you think you could do that?  It's a great way to become familiar with the PR workflow on GitHub. :smile: 

Cheers,
Tony

**Comment by kaumasse** [comment]
Hi Tony, 

I've added a PR https://github.com/tonysneed/trackable-entities/pull/59. It was my first one, if there are errors in workflow etc., please let me know for the upcomming ones.

Mathias

**Comment by tonysneed** [comment]
Thanks Mathias, this was a great catch.  The reason that setting customer to Added did not cascade to related orders and details was that the relation between customer and order was 0-1 to many, and I just had a check for 1 to many.  So I fixed that, and I also noticed a problem with checking the parent TrackingState when I should have been checking the EntityState.

This is a great example of where submitting a Pull Request with a failing test helped me see exactly the behavior, then find and solve the problem.  This was *much easier* than trying to reconstruct the behavior based on comments and hoping I got it right.  Yay Git!

**Comment by tonysneed** [comment]
In order to get the NuGet packages that include the fix, follow the instructions on my blog post on continuous integration via MyGet: http://blog.tonysneed.com/2014/10/25/myget-continuous-integration-for-the-rest-of-us.

**Comment by kaumasse** [comment]
Hi Tony, 

thank you very much. You're right, if there are unit tests in the project your suggested way it's much easier! Hopefully we will not find many more in the future, but on the other hand it makes this solution more robust. I try to get a bit more into your code over the next weeks, so I can maybe provide a solution or more information about the cause next time.

Best regards.
