### ISSUE TITLE
Possible bug while deleting items

### ISSUE THREAD

**Issue by harrisunderwork** [tonysneed/trackable-entities#54]
Hi Tony,

When added items are being deleted from their collection, a code is changing their state to unchanged.

https://github.com/tonysneed/trackable-entities/blob/develop/Source/TrackableEntities.Client/TrackableExtensions.cs#L94

And in the remove method of changetrackingcollection, you are checking this 

https://github.com/tonysneed/trackable-entities/blob/develop/Source/TrackableEntities.Client/ChangeTrackingCollection.cs#L249

It will never be in added state. Aren't they contradicting ?

**Comment by tonysneed** [comment]
That [first snippet](https://github.com/tonysneed/trackable-entities/blob/release-2.5.1/Source/TrackableEntities.Client/TrackableExtensions.cs#L81-99) is taken from an **internal** class, ```TrackableExtensions```, so it's only for internal use in special circumstances and not for public consumption.  For insight into the usage, you should have a look at the unit tests, which express the expected behavior of the framework.  The short answer is that you can pretty much ignore it.

As for the [second snippet](https://github.com/tonysneed/trackable-entities/blob/release-2.5.1/Source/TrackableEntities.Client/ChangeTrackingCollection.cs#L248-251), the logic is that removing an added item should not in fact delete it, because all you're saying is that you don't want to add it.

By the way, when you include snippets in issues or comments, you can link to the source code where they come from, which will help the reviewer see them in context.  Check out [this article](http://shaun.boyblack.co.za/blog/2010/08/19/linking-to-your-github-code/) for info on selecting a tag when linking to lines of code in source.

**Comment by harrisunderwork** [comment]
Hi Tony, just updated the comment. Sorry I am new to Github stuff.

Problem is, when you say removing an added item, the first code snippet actually modifies its state to Unchanged. Therefore second condition is always met and it is adding the entity to its deleted collection.

**Comment by tonysneed** [comment]
For the snippets, you'll want to select the latest tag version first (v2.5.1), then copy the link -- otherwise the line numbers will likely change when the code is later updated (per the article I linked to). :smile: 

You're assuming that SetState gets called before Remove, but I don't think that actually happens.  Do you have a scenario in which you are seeing this happen?  If so, you should create a failing test and submit a pull request, so I can better evaluate the behavior.  Thanks!

**Comment by harrisunderwork** [comment]
Closing this issue as it is dupe of https://github.com/tonysneed/trackable-entities/issues/58
