### ISSUE TITLE
NotMapped entities should not be added in Modified properties

### ISSUE THREAD

**Issue by harrisunderwork** [tonysneed/trackable-entities#57]
Hi Tony,

Let's say I have class Product, now I extended that class by adding more properties in second partial class and added [NotMapped] over them. They may/may not fire propertychanged event. But in any case, they should not be added in ModifiedProperties, right ?

**Comment by tonysneed** [comment]
Hi!

If you are adding a partial class with additional properties, the C# compiler generates a **single class** from the two files.  In order to participate in change tracking, those properties simply need to fire the ```PropertyChanged``` event by calling the ```NotifyPropertyChanged``` method in the ```EntityBase``` class, just like the properties in the generated class.  As a result, it will be included with ```ModifiedProperties```.

The ```[NotMapped]``` attribute really has nothing to do with change tracking, it's for the Entity Framework to let it know that there is not a corresponding column in the mapped table in the database.  My question, however, would be, why would you have non-mapped properties that will be change-tracked, since the purpose of the change tracking is to persist changes to the database?

Cheers,
Tony

**Comment by harrisunderwork** [comment]
Hi Tony, thanks for the response.

There is only single NotifyPropertyChanged event handler that we are using
in both partial classes. Since there is no way to know, if the property
firing the event is ORM property or not, it will definitely be added in
ModifiedProperties collection. Now, when ApplyChanges method is called, no
check is present there too as such when the ApplyChanges method is trying
to change its state, it is throwing exception.

I have modified the TrackableEntities source code to check if the property
has NotMapped attribute, if it has, it is not added to Modifiedproperties
collection.

Any thoughts ?

**Comment by tonysneed** [comment]
It's interesting that you are wishing to change-track properties which are not mapped.  I assume the reason you want to do that is perhaps to perform some other server-side processing.

In that case, what I would suggest is using the EF meta API for seeing if the property is mapped, rather than .NET reflection.  The reason is to accommodate Fluent mappings, as well as model-based (EDMX) mappings.

If you were to take that approach, I would entertain a pull request for the feature.

**Comment by harrisunderwork** [comment]
Would that work in database design approach ? Also, I don't think that
would work on .net clients. I would need edmx file referenced in my client
solution to take advantage of that.

Problem is not change tracking, but NotifiyPropertyChanged event handler,
as it doing two tasks, notify change as well maintain change tracking. If I
replace NotifyPropertyChanged event handler on extended properties, problem
will automatically be solved.

**Comment by harrisunderwork** [comment]
Also, all if your entities are derived from EntityBase, that was creating
problem in my project where the second partial class was derived from some
other base class. Any specific reason why they are not derived from
interface ?

**Comment by tonysneed** [comment]
Perhaps if I understood what you're trying to accomplish, I could provide better guidance.  What is your overall goal?

The only thing that INotifyPropertyChanged does is expose an event, which can be handled for more than one purpose, for example, change tracking and data binding.  It is customary to place the implementation in a base class on the client, but this is not a strict requirement.

Rather than shared entities, you might want to consider using separate entities for your solution.  On the client, you'd have classes derived from EntityBase for change tracking, etc.  But on the server, there is no base class for the entities, just interfaces.

**Comment by harrisunderwork** [comment]
Okay let me get in detailed discussion with you.

We have a system where user can create an insurance policy. That policy can
contain atleast 20 child collections. We are using Microsoft Workflows for
business agility. Now in extended class, we have a property called
businessoperations. It store current businessoperation performed, on the
basis of the business operation, workflow decided the business case. In
that business case, we deal with newly created and old policies. Now when
we modify business operations, it should change the state of policy
accordingly, Unchanged -> Modified and added -> added.

But since this property is not mapped to an orm property, it should not be
entered into modified properties collection. It is just an identifier for
further processing.

We have to use shared entities as agile business processing is done in
workflows, but there are some concrete business logic too, which needs to
be executed on server. Thats why we need same association everywhere.

Second case is, we have divided entities according to their usage, like
MasterDataEntities, WorkflowEntities. Now WCF can't deal with knowntypes on
interfaces, we had to create concrete types and derive entities from them.

For now, I have removed derivation from Entitybase and changed everywhere
to IEntity and other interfaces, which is implemented by EntityBase.

Also, I have used t4 templates of ef4 and modified it accordingly to use
ChangeTrackingCollection. Reason being Fixup methods.

Actually our system is not a simple client server architecture, we have
atleast 20 services doing different kinds of operations and an entity can
travel between 4 to 8 services at a time.

**Comment by tonysneed** [comment]
Thanks for explaining your scenario more completely -- this helps. :smile:

Your use of interfaces and customization of T4 templates sounds fine, as it will allow you to use your own base class, which allows you to use shared entities and also perform change-tracking both on the client and among multiple services.  I'm also glad you were able to incorporate the relationship fixup methods.

From your first paragraph, I understand that you have an unmapped PolicyState property which should be set based on a BusinessOperations property.  Rather than customizing ApplyChanges, I would recommend you simply subscribe to the PropertyChanged event of the entity or entities.  When the event fires, you'll get information about which property was changed, and on this basis you can set the PolicyState property in order to drive your workflow process.  Note that you can explicitly exclude properties from change tracking, for example, any non-mapped properties.  Does it sound like this approach might work for you?

**Comment by harrisunderwork** [comment]
Yes, initially I thought to use ExcludedProperties place holder, but since
most developers were unwilling to make the change, I had to sought
something at framework level. I have not made changes in ApplyChanges() but
OnPropertyChanged() method, to check if the property changed is not a
NotMapped property. So bascially, if the property is not added in the list,
everything works fine in ApplyChanges() method.

Actually I have lot of questions to ask, so can I ask in this thread itself
instead of creating multiple threads ?

**Comment by tonysneed** [comment]
I see, that's fine ... ExcludedProperties simply ignores the PropertyChanged event for those properties, so not firing the event to being with accomplished the same thing.

Probably best to create a new Issue for each question, so others can better locate and make sense of the information.

**Comment by harrisunderwork** [comment]
ModifiedProperties is ICollection and that was creating problems in XmlSerialization (yes we still use it as we have legacy systems too to feed the data :) )

I have changed it List<string> wherever required.

**Comment by tonysneed** [comment]
Sure, that's fine.

**Comment by harrisunderwork** [comment]
Please close the issue. I have put check of NonMapped attribute wherever required.
