### ISSUE TITLE
InvalidOperationException uncaught in an MVC Application

### ISSUE THREAD

**Issue by DavidRogersDev** [tonysneed/trackable-entities#82]
Hi Tony, I like the idea of trackable-entities and am familiar with the concept of self-tracking entities and painting the state.

I finally got around to evaluating your project in the context of an ASP.NET MVC application and am not sure what I am doing wrong. The scenario I have in my proof-of-concept is that I am changing a value in a child object of the top-level object (there's no challenge in just changing a property in the top object of the graph).

I track state using javascript on the client and when the modelbinder deserializes the entity, the TrackingState property of that child item is in the correct state i.e. modified.

My first call is to ApplyChanges: licenseContext.ApplyChanges(licence);

This throws the following exception:

Additional information: Attaching an entity of type 'Licensing.Entities.Entities.Service.Net45.Models.LicenceAllocation' failed because another entity of the same type already has the same primary key value. This can happen when using the 'Attach' method or setting the state of an entity to 'Unchanged' or 'Modified' if any entities in the graph have conflicting key values. This may be because some entities are new and have not yet received database-generated key values. In this case use the 'Add' method or the 'Added' entity state to track the graph and then set the state of non-new entities to 'Unchanged' or 'Modified' as appropriate.

I can give more information if required. It's always hard to know how much info is enough to give when raising issues.

Obviously, on the client, I'm not using ChangeTrackingCollection (as it is not rich client). Could that be why it is not working? Does the object need to have been returned from changeTracker.GetChanges() ?

Thanks

**Comment by tonysneed** [comment]
@DavidRogersDev,

Sorry I wasn't able to respond earlier to this issue.  This is an Entity Framework error that usually comes up when the entity state has not been set properly.  See this [article](changeTracker.GetChanges()) for more info.  Calling `changeTracker.GetChanges()` will return an object graph where tracking state has been set properly.  So what I would suggest is that you try that from a test rich client, and then paint your state from JavaScript so that it matches.

If you are still getting the error, it's best to create a failing test in a pull request, so that we can see if there's a bug that needs fixing.

Cheers,
Tony

**Comment by tonysneed** [comment]
As this is rather stale at this point, I'm closing this issue for now.  However, if warranted, I'll be happy to re-open it.

**Comment by DavidRogersDev** [comment]
I've revisited this and there is something I am definitely not comprehending. I've rendered data in inputs on a web page, then sent them straight back to the server without changing anything. With unmodified state, I am getting the same exception.

I can't reproduce in a test. It is definitely my use that seems to be the problem. I don't suppose you have a HTML/Javascript sample lying around?

**Comment by tonysneed** [comment]
Hi there!

From the error description, it sounds like EF is complaining that you are missing key values in your entities.  If they entities are in an Added state, then of course you don't need the key values, and you should not set them, because the database will provide those when the entities are saved.  So if the entities come from the database and already have key values, you need to check to make sure the primary key values have made it to the service.  If the entities are new and to be added to the database, then make sure that the key values are *not* supplied (zero, for example).

If you are still having issues, I'd be happy to take a look at your code.  Just create a small repro, then either put it on GitHub, where I can clone it, or upload it to something like DropBox.  GitHub would be best, but I'll take it anyway I can. :smile: Then it should be fairly easy for me to see what you're doing and the reason for the error.

Cheers,
Tony

**Comment by DavidRogersDev** [comment]
Thanks very much Tony. That would be awesome. I'll take a bit of time to clean the solution up, but I'll get it up in a repo in the near future. I'll report back here with a clone url. Cheers.

**Comment by DavidRogersDev** [comment]
Hi Tony, as per my last comment, here is that clone uri https://github.com/DavidRogersDev/TrackableEntitiesAspMVCSample.git

There's no rush on this at all. Whenever you get around to it. I'm very glad that you're happy to take a look at it.

**Comment by tonysneed** [comment]
Got it, thanks!  Forking and cloning now ...

**Comment by tonysneed** [comment]
Hi @DavidRogersDev, How can I restore the database from the .bak file you provided? I tried changing the extension to .mdf and attaching via SQL Mant Studio, but there's an error stating that the file is not a primary database file.

**Comment by tonysneed** [comment]
There were some things wrong with how you created the git repo, which made it difficult to restore packages and build the project.  For example, you should exclude the packages folder via your .gitignore file.  So I submitted the following pull request to include corrections for these problems: DavidRogersDev/TrackableEntitiesAspMVCSample#1

Please merge the pull request, so that we can be in sync.

The other thing I did was to create a client entities project for use by the TestHarness project, and I refactored the test harness to post to the controller action in your MVC project, rather than query the database directly.

Once you give me the database file, I'll be able to populate the database with data and create some tests to see why you're getting the InvalidOperationException.

**Comment by tonysneed** [comment]
I submitted a second pull request with my updates: DavidRogersDev/TrackableEntitiesAspMVCSample#2.  Please merge the PR to sync.

I was able to persist changes using your EditController actions from the *TestHarness* rich client.

When debugging the `EditLicence` action from the web app by clicking the 'click' button, I noticed that `TrackingState` is set to `Unchanged`.  So I debugged the client using Chrome and observed that the call to `EditLicence` is passing a `licence` JSON with `trackingState` set to **0**, when it should have been set to **2**.

So it seems your problem has to do with your Angular data binding or JavaScript, which is not setting the `TrackingState` property properly.  I don't know enough about Angular to tell you how to correct the problem.  But I think this is most likely the answer you're looking for.

**Comment by DavidRogersDev** [comment]
Thanks very much Tony. I'll take a good look at this tonight after work. Let me know if you have some kind of Paypal donate button anywhere - I'll happily buy you a couple of coffees. Cheers.

**Comment by DavidRogersDev** [comment]
Thanks Tony. I confirm I was making a bit of a noob error. I was sending the entity down the pipe with a state of unchanged. I believe that before populating the page, the entity (and descendants) should be set to modified, whether they are actually changed or not. As you noted, it works fine when sending data back to the server with the state of modified. It also worked fine when I changed the state of the licence entity to Deleted in the debugger (at the server). The Licence was, in fact, deleted.

Thanks again Tony, and let me know if I can buy you a couple of coffees or some such :)

**Comment by tonysneed** [comment]
Glad it all worked out! Yes, I'm happy to accept donations, and it encourages me to continue to maintain and improve the project.  You can send funds via PayPal using my email: tony@tonysneed.com (select Friends or family).  And I do like coffee! :coffee:
